name: 'The title of your GitHub Action'
description: 'The description of your GitHub Action'
branding:
  icon: activity
  color: orange
inputs:
  owner:
    description:
      'The owner of the repo. Assign from github.repository_owner. Example, "dotnet".'
    required: true
  name:
    description:
      'The repository name. Example, "samples".'
    required: true
  branch:
    description:
      'The branch name. Assign from github.ref. Example, "refs/heads/main".'
    required: true
  dir:
    description:
      'The root directory to work from. Examples, "path/to/code".'
    required: false
    default: '/github/workspace'
  repository:
    description:
      'Repository. Examples, "path/to/code".'
    required: false
  pathHead:
    description:
      'Path where to save the curret commit repo.'
    required: false
  pathBase:
    description:
      'Path where to save the prev commit repo.'
    required: false
  after:
    description:
      'Commit that triggered the workflow.'
    required: false
  before:
    description:
      'Commit before the last one.'
    required: false
  token:
    description:
      'Token, "path/to/code".'
    required: false
outputs:
  summary-title:
    description:
      'The title of the code metrics action.'
  summary-details:
    description:
      'A detailed summary of all the projects that were flagged.'
  updated-metrics:
    description:
      'A boolean value, indicating whether or not the action updated metrics.'
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v2
    with:
      ref: ${{ inputs.after }} #'main' new commit
      path: ${{ inputs.pathHead }} 
  - uses: actions/checkout@v2
    with:
      fetch-depth: 2
      ref: ${{ inputs.before }} #'new' previous commit
      path: ${{ inputs.pathBase }} 
      
  - name: Run code analysis last commit
    id: this-app
    uses: rijadge/NDiff-testing@release1.10
    env:
      GREETINGS: 'Hello, .NET developers!' 
    with:
      owner: ${{ inputs.owner }}
      name: ${{ inputs.repository }}
      branch: ${{ inputs.branch }}
      dir: ${{ "./" + inputs.pathHead }}
      repository: ${{ inputs.repository}}
      token: ${{ inputs.token }}
      
  - name: Run code analysis prev commit
    id: this-app
    uses: rijadge/NDiff-testing@release1.10
    env:
      GREETINGS: 'Hello, .NET developers!' 
    with:
      owner: ${{ inputs.owner }}
      name: ${{ inputs.repository }}
      branch: ${{ inputs.branch }}
      dir: ${{ "./" + inputs.pathBase }}
      repository: ${{ inputs.repository}}
      token: ${{ inputs.token }}
  - run: |
     ls
     echo =============================
     cd head
     ls
     echo =============================
     cd ..
     cd base
     ls
